### ISSUE TITLE
guzzleのフル機能を開放して欲しい

### ISSUE THREAD

**Issue by hirak** [cloudpack/Rorschach#5]
今のRorschachだと、`headers` と `body` のみを指定できるようになっています。

しかし、bodyパラメータはstring指定限定であり、せっかくyamlで書けるのに不便です。
POSTリクエスト時に、bodyにハッシュを配置するとエラーになってしまいました。
今のguzzleだと、form_params/multipart/json/bodyの使い分けが必要なようです。

``` yaml
[InvalidArgumentException] Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or a the "multipart" request option to send a multipart/form-data request.
```

jsonをbodyに指定して投げつける形式のwebapiもさほど珍しくはありませんので、個人的にもこれは全種類指定できるようになって欲しいです。

で、思ったのですが、わざわざRorschachでオプションの組み立てなどせずに、そのまま丸ごとguzzleに渡してしまえばいいのではないでしょうか？

https://github.com/cloudpack/Rorschach/blob/5e070ec72e6d2b75092d9b32f8df6967d075b069/src/Resource/Entity.php#L105-L108

こうじゃなくて、まるっと渡しちゃう感じ。

``` php
        $response = $this->guzzle->request(
            $resource['method'],
            $resource['url'],
            $resource
        );
// $resource['options'] とかを定義して押し込めてもいいかも
```

これなら、POSTのパラメータ指定方法も詳しくyamlで記述できますし、何よりguzzleのほぼ全機能が使えるようになります。
guzzleのアップデートによってInterfaceが変わるリスクはありますが、いざとなればライブラリ利用者側でguzzleのバージョン固定しちゃえばいいので、さほど問題にはならないと思います。

開発方針次第だと思ったので一旦issueにしました。もしよかったらP-R作ります。

**Comment by shinichi-takahashi** [comment]
@hirak 
bodyに関して、完全にサボった結果が反映されてるだけですのでお許し下さい。
時流的にRorschachはJSON限定対応でいいと思ってますが、柔軟に対応できるなら（多少無理矢理感があっても）他も対応したい、って具合です。

header等の組み立てについては、おっしゃる通りです。
そのまま `$resource` を渡すよりは、別に押し込みたいですね。

**Comment by shinichi-takahashi** [comment]
@hirak 
対応してみました。
あかんようやったらReopenして再度ご指摘お願いします。
