### ISSUE TITLE
40Xや50Xのハンドリング

### ISSUE THREAD

**Issue by hirak** [cloudpack/Rorschach#6]
40Xや50X系のレスポンスが発生した際、guzzleが例外を投げるので、アサーションにたどり着かないようです。

```
  [GuzzleHttp\Exception\ClientException]                                                                                                   
  Client error: `POST https://example.com/api` resulted in a `400 Bad Request` response:                            
  {"result":... (truncated...)
```

guzzleのオプションに `'http_errors' => false,` を追加したら40X系などを例外扱いしなくなるので直りそうですが、
[guzzleのフル機能を開放して欲しい · Issue #5 · cloudpack/Rorschach](https://github.com/cloudpack/Rorschach/issues/5)
と修正範囲が似ているので、方針を先にお聞きしたいです。

**Comment by shinichi-takahashi** [comment]
@hirak 
そうですねぇ...。フル機能開放したらそれで終わりだよね、って話ですよね？
デフォルトオプションとして中で指定しておく、って感じにしたいとおもいます。
allow_redirectについて、同様の措置を取ろうと思っているので、こちらでチョメチョメしておきます。

ご意見ありがとうございます。

**Comment by shinichi-takahashi** [comment]
@hirak 
方針は #5 の返答を参照でお願いします。
一旦やりました。
