### ISSUE TITLE
URI埋め込み記法は`{}`を使って欲しい

### ISSUE THREAD

**Issue by hirak** [cloudpack/Rorschach#7]
細かい話なのですが、URIの構文上、 `()` は素のまま登場しうる文字として定義されています。
https://tools.ietf.org/html/rfc3986#section-2.2

構文として()を使うURL設計はあまり見かけないですし、非予約文字である空白文字を含まないと発動しないようなので大丈夫かもしれませんが、読みにくくなるケースがあるかもしれません。

個人的には、URI Templateを真似て `{}` をデリミタとして使うことをおすすめします。 `{}` はパーセントエンコーディングしないと登場しないはずなので、URI自体と混ざりません。
https://tools.ietf.org/html/rfc6570

**Comment by shinichi-takahashi** [comment]
@hirak 
こちら、 `symfony/yaml::parse()` で文中の `{{ }}` でエラーはいちゃいます。
なので最初は `{{ }}` でやってたんですけど、 `(( ))` にしてます。
対応するなら一回別のデリミタにして `parse()` が通るようにして〜...って感じになりますね。
一旦こちらもリファクタ対応を行います。

ご意見ありがとうございます！

**Comment by hirak** [comment]
おおお、、`symfony/yaml` がネックなのか。。了解しました。

**Comment by shinichi-takahashi** [comment]
とかいいつつやりました。
